export const channelsppl = [
    {name: "football", icon: ["f"], desc: "latest match and news", id: 34705},
    {name: "anime", icon: ["a"], desc: "the world of weebs", id: 19808},
    {name: "what new?", icon: ["w"], desc: "", id: 35199},
    {name: "new", icon: ["n"], desc: "wassap↵", id: 18096},
    {name: "bom", icon: ["b"], desc: "asd", id: 86988},
    {name: "techTalks", icon: ["tt"], desc: "Exploring the latest in technology", id: 45672},
    {name: "foodieFiesta", icon: ["ft"], desc: "A culinary adventure around the world", id: 87965},
    {name: "artisticVibes", icon: ["a"], desc: "Unlocking creativity through art", id: 23341},
    {name: "gamingGurus", icon: ["g"], desc: "Level up with the best gaming tips and tricks", id: 56789},
    {name: "travelTales", icon: ["t"], desc: "Embark on unforgettable journeys", id: 78654}
    ];


  export  const chat = [
        { id: 34705, hours: 13, min: 6, text: "asdasd", day: 4, name: "John" },
        { id: 34705, hours: 9, min: 42, text: "Lorem ipsum", day: 5, name: "Emily" },
        { id: 34705, hours: 16, min: 20, text: "Dolor sit amet", day: 6, name: "Michael" },
        { id: 34705, hours: 10, min: 15, text: "Consectetur adipiscing elit", day: 7, name: "Sarah" },
        { id: 34705, hours: 8, min: 30, text: "Nulla facilisi", day: 8, name: "David" },
        { id: 19808, hours: 14, min: 55, text: "Pellentesque habitant morbi tristique senectus", day: 9, name: "Sophia" },
        { id: 19808, hours: 11, min: 10, text: "Fusce id ipsum nec mauris tempus", day: 10, name: "Daniel" },
        { id: 19808, hours: 17, min: 45, text: "Vivamus ut justo ut urna tristique pretium", day: 11, name: "Olivia" },
        { id: 19808, hours: 15, min: 25, text: "Aliquam erat volutpat", day: 12, name: "Matthew" },
        { id: 19808, hours: 12, min: 5, text: "Maecenas luctus libero id nisl tincidunt", day: 13, name: "Emma" },
        { id: 35199, hours: 19, min: 18, text: "Cras sed libero maximus", day: 14, name: "Jacob" },
        { id: 35199, hours: 16, min: 50, text: "Etiam condimentum", day: 15, name: "Ava" },
        { id: 35199, hours: 10, min: 35, text: "Vestibulum tempor finibus nunc", day: 16, name: "William" },
        { id: 35199, hours: 13, min: 22, text: "Nam interdum urna et mauris finibus", day: 17, name: "Isabella" },
        { id: 35199, hours: 9, min: 15, text: "Ut non justo placerat", day: 18, name: "Mason" },
        { id: 18096, hours: 14, min: 48, text: "Morbi ut congue dui", day: 19, name: "Sophia" },
        { id: 18096, hours: 11, min: 30, text: "Sed dapibus lectus elit", day: 20, name: "Ethan" },
        { id: 18096, hours: 18, min: 5, text: "Praesent id turpis fringilla", day: 21, name: "Olivia" },
        { id: 18096, hours: 15, min: 40, text: "Donec scelerisque", day
      
      : 22, name: "Noah" },
        { id: 18096, hours: 12, min: 20, text: "Quisque ut erat gravida", day: 23, name: "Charlotte" }
        ,
            { id: 86988, hours: 13, min: 6, text: "asdasd", day: 4, name: "John" },
            { id: 86988, hours: 9, min: 42, text: "Lorem ipsum", day: 5, name: "Emily" },
            { id: 86988, hours: 16, min: 20, text: "Dolor sit amet", day: 6, name: "Michael" },
            { id: 86988, hours: 10, min: 15, text: "Consectetur adipiscing elit", day: 7, name: "Sarah" },
            { id: 86988, hours: 8, min: 30, text: "Nulla facilisi", day: 8, name: "David" },
            { id: 86988, hours: 14, min: 55, text: "Pellentesque habitant morbi tristique senectus", day: 9, name: "Sophia" },
            { id: 45672, hours: 11, min: 10, text: "Fusce id ipsum nec mauris tempus", day: 10, name: "Daniel" },
            { id: 45672, hours: 17, min: 45, text: "Vivamus ut justo ut urna tristique pretium", day: 11, name: "Olivia" },
            { id: 45672, hours: 15, min: 25, text: "Aliquam erat volutpat", day: 12, name: "Matthew" },
            { id: 45672, hours: 12, min: 5, text: "Maecenas luctus libero id nisl tincidunt", day: 13, name: "Emma" },
            { id: 45672, hours: 19, min: 18, text: "Cras sed libero maximus", day: 14, name: "Jacob" },
            { id: 45672, hours: 16, min: 50, text: "Etiam condimentum", day: 15, name: "Ava" },
            { id: 87965, hours: 10, min: 35, text: "Vestibulum tempor finibus nunc", day: 16, name: "William" },
            { id: 87965, hours: 13, min: 22, text: "Nam interdum urna et mauris finibus", day: 17, name: "Isabella" },
            { id: 87965, hours: 9, min: 15, text: "Ut non justo placerat", day: 18, name: "Mason" },
            { id: 87965, hours: 14, min: 48, text: "Morbi ut congue dui", day: 19, name: "Sophia" },
            { id: 87965, hours: 11, min: 30, text: "Sed dapibus lectus elit", day: 20, name: "Ethan" },
            { id: 87965, hours: 18, min: 5, text: "Praesent id turpis fringilla", day: 21, name: "Olivia" },
            { id: 56789, hours: 15, min: 40, text: "Donec scelerisque", day
          
          : 22, name: "Noah" },
            { id: 56789, hours: 12, min: 20, text: "Quisque ut erat gravida", day: 23, name: "Charlotte" },
            { id: 56789, hours: 14, min: 10, text: "Faucibus ornare", day: 24, name: "Liam" },
            { id: 56789, hours: 16, min: 55, text: "Interdum et malesuada fames", day: 25, name: "Sophie" },
            { id: 56789, hours: 11, min: 45, text: "Etiam sollicitudin consectetur", day: 26, name: "Benjamin" },
            { id: 56789, hours: 9, min: 30, text: "Pellentesque habitant", day: 27, name: "Amelia" },
            { id: 56789, hours: 13, min: 15, text: "Aliquam venenatis risus", day: 28, name: "James" },
            { id: 78654, hours: 10, min: 5, text: "Vivamus malesuada", day: 29, name: "Aria" },
            { id: 78654, hours: 15, min: 50, text: "Suspendisse vehicula", day: 30, name: "Alexander" },
            { id: 78654, hours: 12, min: 40, text: "Quisque tempus lacus", day: 31, name: "Grace" },
            { id: 78654, hours: 18, min: 25, text: "Nullam eget urna", day: 32, name: "Henry" },
            { id: 23341, hours: 14, min: 20, text: "Mauris nec efficitur", day: 33, name: "Scarlett" },
            { id: 23341, hours: 16, min: 15, text: "Fusce non dolor", day: 34, name: "Lucas" },
            { id: 23341, hours: 10, min: 55, text: "Proin sed purus", day: 35, name: "Chloe" },
            { id: 23341, hours: 13, min: 35, text: "Vestibulum ante ipsum", day: 36, name: "Elijah" },
            { id: 23341, hours: 9, min: 25, text: "Pellentesque mattis", day: 37, name: "Zoe" },
            { id: 23341, hours: 12, min: 15, text: "Morbi rhoncus tincidunt", day: 38, name: "Jackson" }
      ];